apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-app-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resume-app
  template:
    metadata:
      labels:
        app: resume-app
    spec:
      containers:
        - name: resume-app
          image: davidhod95/resume:0.0.1
          env: 
            - name: hostname
              value: "db"
            - name: port
              value: "5432"
            - name: user
              value: "postgres"
            - name: password
              value: "postgres"
            - name: dbname
              value: "postgres"
          ports:
            - containerPort: 8000


---


apiVersion: v1
kind: Service
metadata:
  name: resume-app-service
spec:
  type: NodePort
  selector:
    app: resume-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8001
