apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-app-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resume-app
  template:
    metadata:
      labels:
        app: resume-app
    spec:
      containers:
        - name: resume-appl
          image: davidhod95/resume:resume
          imagePullPolicy: Always
          resources:
            limits:
              memory: "2Gi"
              cpu: "1000m"
          env: 
            - name: hostname
              value: "resume-db-service"
            - name: port
              value: "5432"
            - name: user
              value: "postgres"
            - name: password
              value: "postgres"
            - name: dbname
              value: "postgres"
          ports:
            - containerPort: 8000


---


apiVersion: v1
kind: Service
metadata:
  name: resume-app-service
spec:
  selector:
    app: resume-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000
