version: '3'
services:
  app:
    image: davidhod95/resume:resume
    container_name: resume-app
    environment:
      - hostname=${hostname}
      - port=${port}
      - user=${user}
      - password=${password}
      - dbname=${dbname}
    ports: 
      - "8000:8000"
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy    

  db:
    container_name: resume-db
    image: postgres:latest
    user: ${user}
    environment:
      - POSTGRES_USER=${user}
      - POSTGRES_PASSWORD=${password}
      - POSTGRES_DB=${dbname}
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - resume_db:/var/lib/postgresql/data
      - ./resume.sql:/docker-entrypoint-initdb.d/resume.sql

volumes:               
  resume_db: 