apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-app-depl
  namespace: resume

spec:
  replicas: 1
  selector:
    matchLabels:
      app: resume-app
  template:
    metadata:
      labels:
        app: resume-app

    spec:
      containers:
        - name: resume-appl
          image: davidhod95/resume:resume
          imagePullPolicy: Always
          resources:
            limits:
              memory: "2Gi"
              cpu: "1000m"

          env: 
            - name: hostname
              valueFrom:
                configMapKeyRef:
                  name: resume-app-configmap 
                  key: hostname

            - name: port
              valueFrom:
                configMapKeyRef:
                  name: resume-app-configmap 
                  key: port

            - name: user
              valueFrom: 
                secretKeyRef:
                  name: resume-app-secret
                  key: user

            - name: password
              valueFrom: 
                secretKeyRef:
                  name: resume-app-secret
                  key: password

            - name: dbname
              valueFrom: 
                secretKeyRef:
                  name: resume-app-secret
                  key: dbname

          ports:
            - containerPort: 8000


---


apiVersion: v1
kind: Service
metadata:
  name: resume-app-service
  namespace: resume
  
spec:
  selector:
    app: resume-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000


---


apiVersion: v1
kind: ConfigMap
metadata:
  name: resume-app-configmap
  namespace: resume
data:
  hostname: resume-db-service
  port: "5432"


---


apiVersion: v1
kind: Secret
metadata:
  name: resume-app-secret
  namespace: resume
type: Opaque
data:
  user: cG9zdGdyZXM=
  password: cG9zdGdyZXM=
  dbname: cG9zdGdyZXM=